### ISSUE TITLE
WordMachine - Failing

### ISSUE THREAD

**Issue by samjoshuaberchmans** [rasmusfranke/codility#1]
Hi , 

i had tried to use the WordMachine snippet. 

When adding a main function and passing string to solution() method , it fails with the following error.
Exception in thread "main" java.lang.NullPointerException
	at projectCCPA.WordMachine1.applyCommand(WordMachine1.java:35)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at projectCCPA.WordMachine1.solution(WordMachine1.java:24)
	at projectCCPA.WordMachine1.main(WordMachine1.java:80)

Let me know if you are aware of the same and fixed this issue.

Thanks in Advance.

**Comment by ePaul** [comment]
Hi, this happens when your input string contains illegal operations.

(I guess it could be handled better, but this was not part of the assignment.)
